### ISSUE TITLE
Error při pokusu o výpisu známek

### ISSUE THREAD

**Issue by Sap1k** [rpsloup/bakalari-cli#21]
Při pokusu o výpis známek na API verze 3.25.0 dojde k chybě - viz. níže
`[xxxx@bakalari]$ marks
file:///C:/Users/Sap1k/Documents/bakalari-cli-1.0.4/src/functions/commandFunctions.ts:32
  C_GREEN,
                      ^
TypeError: Cannot read properties of null (reading 'trim')
    at file:///C:/Users/Sap1k/Documents/bakalari-cli-1.0.4/src/functions/commandFunctions.ts:219:63
    at Array.map (<anonymous>)
    at file:///C:/Users/Sap1k/Documents/bakalari-cli-1.0.4/src/functions/commandFunctions.ts:219:26
    at step (file:///C:/Users/Sap1k/Documents/bakalari-cli-1.0.4/src/functions/commandFunctions.ts:32:23)
    at Object.next (file:///C:/Users/Sap1k/Documents/bakalari-cli-1.0.4/src/functions/commandFunctions.ts:13:53)
    at fulfilled (file:///C:/Users/Sap1k/Documents/bakalari-cli-1.0.4/src/functions/commandFunctions.ts:4:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)`

Také u absence chybí absence, která není omluvená, ale to je rozbité i v aplikace, tudíž to beru jako cerifikovaný BakaFuckup :D 

Díky moc za čas a pozornost!

**Comment by rpsloup** [comment]
Ahoj, moc děkuji za nalezení issue. Dnes udělám branch na bugfix a ideálně i mergnu do masteru!

**Comment by rpsloup** [comment]
#22, tento PR je merged do master a měl by řešit problém. Poprosím tedy o zpětnou vazbu. Dle všeho se může stát, že AverageText samotný může být null, proto na něj nefunguje string metoda `.trim()`, která program ukončí.
